### ISSUE TITLE
This presentation doesn't need to be in a repository.

### ISSUE THREAD

**Issue by katyhuff** [arfc/2019-chee-twofcs#3]
pptx and pdf files aren't conducive to version control with git. Additionally, the paper in the repository is on the Cyder topic (not the topic of the talk.) Perhaps the only archiving that is necessary for this presentation is to : 

- [x] put it on the website in pdf form (in 'presentations')
- [x] put it in zotero in both pdf and pptx formats

Then, this repository can/should be deleted.

**Comment by gwenchee** [comment]
Done! I will delete this repository now.
